#cloud-config
autoinstall:
  version: 1
  
  # Locale and keyboard
  locale: en_US.UTF-8
  keyboard:
    layout: us
    variant: ''
  
  # Network configuration - disable IPv6
  network:
    version: 2
    ethernets:
      eno1:
        dhcp4: true
        dhcp6: false
  
  # Kernel selection - 6.11 HWE kernel
  kernel:
    flavor: hwe
  
  # Enable third-party software and drivers
  drivers:
    install: true
  
  # Third-party software repositories
  apt:
    sources:
      multiverse:
        source: "deb http://archive.ubuntu.com/ubuntu $RELEASE multiverse"
      multiverse-updates:
        source: "deb http://archive.ubuntu.com/ubuntu $RELEASE-updates multiverse"
  
  # Storage configuration - single disk with LVM, ready for post-install mirroring
  storage:
    config:
      # Primary NVMe disk (nvme1n1 left untouched for later mirroring)
      - type: disk
        id: disk0
        path: /dev/nvme0n1
        wipe: superblock-recursive
        preserve: false
        grub_device: true
      
      # EFI system partition (512MB)
      - type: partition
        id: efi_partition
        device: disk0
        size: 512M
        flag: boot
        preserve: false
      
      # LVM partition (remaining space - boot will be on LVM)
      - type: partition
        id: lvm_partition
        device: disk0
        size: -1
        preserve: false
      
      # LVM volume group
      - type: lvm_volgroup
        id: vg0
        name: ubuntu-vg
        devices:
          - lvm_partition
        preserve: false
      
      # Boot logical volume (4GB)
      - type: lvm_partition
        id: lv_boot
        name: boot
        volgroup: vg0
        size: 4G
        preserve: false
      
      # Root logical volume (1TB)
      - type: lvm_partition
        id: lv_root
        name: root
        volgroup: vg0
        size: 1T
        preserve: false
      
      # Format EFI partition
      - type: format
        id: efi_format
        volume: efi_partition
        fstype: fat32
        preserve: false
      
      # Format boot LV
      - type: format
        id: boot_format
        volume: lv_boot
        fstype: ext4
        preserve: false
      
      # Format root LV
      - type: format
        id: root_format
        volume: lv_root
        fstype: ext4
        preserve: false
      
      # Mount points
      - type: mount
        id: efi_mount
        device: efi_format
        path: /boot/efi
      
      - type: mount
        id: boot_mount
        device: boot_format
        path: /boot
      
      - type: mount
        id: root_mount
        device: root_format
        path: /
  
  # User configuration
  identity:
    hostname: ubuntu-desktop
    username: ubuntu
    # Generate with: openssl passwd -6 adm.Test (generates random salt automatically)
    password: '$6$salt$LgUFV8K47KGR3Wt.L/vE6/8nJa1z2Vz9mGzh5aB3c4F6Pt0rS8Nw2x1B9Ml4K6V8J2H3G5pQ7t4R6S1u3W5y9.'
    realname: Ubuntu User
  
  # SSH configuration
  ssh:
    install-server: true
    allow-pw: true
    authorized-keys: []
      # Add your SSH public keys here if needed
      # - "ssh-rsa AAAAB3NzaC1yc2E... user@host"
  
  # Package selection including third-party software
  packages:
    - openssh-server
    - curl
    - wget
    - vim
    - htop
    - lvm2
    - ubuntu-restricted-extras  # Third-party codecs and fonts
    - ubuntu-drivers-common     # Driver management tools
    - linux-firmware           # Additional firmware
  
  # Updates and upgrades
  updates: security
  
  # Late commands for final configuration
  late-commands:
    # Install and configure additional drivers automatically
    - curtin in-target --target=/target -- ubuntu-drivers autoinstall
    # Update GRUB for UEFI setup
    - curtin in-target --target=/target -- update-grub
    # Update initramfs
    - curtin in-target --target=/target -- update-initramfs -u
    # Disable IPv6 permanently in sysctl
    - curtin in-target --target=/target -- sh -c 'echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf'
    - curtin in-target --target=/target -- sh -c 'echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.conf'
    - curtin in-target --target=/target -- sh -c 'echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.conf'
    # Add IPv6 disable to GRUB kernel parameters
    - curtin in-target --target=/target -- sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="[^"]*/& ipv6.disable=1/' /etc/default/grub
    - curtin in-target --target=/target -- update-grub
  
  # Reboot after installation
  shutdown: reboot
